// Autogenerated by Thrift Compiler (0.10.0)
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

package mars

import (
	"bytes"
	"fmt"
	"gitlab.kingbay-tech.com/engine-lottery/magneto/pkg/thrift.git/lib/go/thrift"
	"gitlab.kingbay-tech.com/engine-lottery/magneto/pkg/bc/base"

)

// (needed to ensure safety because of naive import list construction.)
var _ = thrift.ZERO
var _ = fmt.Printf
var _ = bytes.Equal

var _ = base.GoUnusedProtection__
type MarsService interface {
  // Parameters:
  //  - Req
  //  - Trace
  PublicInterface(req *base.MarsRequest, trace *base.Trace) (r *base.MarsResponse, err error)
}

type MarsServiceClient struct {
  Transport thrift.TTransport
  ProtocolFactory thrift.TProtocolFactory
  InputProtocol thrift.TProtocol
  OutputProtocol thrift.TProtocol
  SeqId int32
}

func NewMarsServiceClientFactory(t thrift.TTransport, f thrift.TProtocolFactory) *MarsServiceClient {
  return &MarsServiceClient{Transport: t,
    ProtocolFactory: f,
    InputProtocol: f.GetProtocol(t),
    OutputProtocol: f.GetProtocol(t),
    SeqId: 0,
  }
}

func NewMarsServiceClientProtocol(t thrift.TTransport, iprot thrift.TProtocol, oprot thrift.TProtocol) *MarsServiceClient {
  return &MarsServiceClient{Transport: t,
    ProtocolFactory: nil,
    InputProtocol: iprot,
    OutputProtocol: oprot,
    SeqId: 0,
  }
}

// Parameters:
//  - Req
//  - Trace
func (p *MarsServiceClient) PublicInterface(req *base.MarsRequest, trace *base.Trace) (r *base.MarsResponse, err error) {
  if err = p.sendPublicInterface(req, trace); err != nil { return }
  return p.recvPublicInterface()
}

func (p *MarsServiceClient) sendPublicInterface(req *base.MarsRequest, trace *base.Trace)(err error) {
  oprot := p.OutputProtocol
  if oprot == nil {
    oprot = p.ProtocolFactory.GetProtocol(p.Transport)
    p.OutputProtocol = oprot
  }
  p.SeqId++
  if err = oprot.WriteMessageBegin("PublicInterface", thrift.CALL, p.SeqId); err != nil {
      return
  }
  args := MarsServicePublicInterfaceArgs{
  Req : req,
  Trace : trace,
  }
  if err = args.Write(oprot); err != nil {
      return
  }
  if err = oprot.WriteMessageEnd(); err != nil {
      return
  }
  return oprot.Flush()
}


func (p *MarsServiceClient) recvPublicInterface() (value *base.MarsResponse, err error) {
  iprot := p.InputProtocol
  if iprot == nil {
    iprot = p.ProtocolFactory.GetProtocol(p.Transport)
    p.InputProtocol = iprot
  }
  method, mTypeId, seqId, err := iprot.ReadMessageBegin()
  if err != nil {
    return
  }
  if method != "PublicInterface" {
    err = thrift.NewTApplicationException(thrift.WRONG_METHOD_NAME, "PublicInterface failed: wrong method name")
    return
  }
  if p.SeqId != seqId {
    err = thrift.NewTApplicationException(thrift.BAD_SEQUENCE_ID, "PublicInterface failed: out of sequence response")
    return
  }
  if mTypeId == thrift.EXCEPTION {
    error0 := thrift.NewTApplicationException(thrift.UNKNOWN_APPLICATION_EXCEPTION, "Unknown Exception")
    var error1 error
    error1, err = error0.Read(iprot)
    if err != nil {
      return
    }
    if err = iprot.ReadMessageEnd(); err != nil {
      return
    }
    err = error1
    return
  }
  if mTypeId != thrift.REPLY {
    err = thrift.NewTApplicationException(thrift.INVALID_MESSAGE_TYPE_EXCEPTION, "PublicInterface failed: invalid message type")
    return
  }
  result := MarsServicePublicInterfaceResult{}
  if err = result.Read(iprot); err != nil {
    return
  }
  if err = iprot.ReadMessageEnd(); err != nil {
    return
  }
  value = result.GetSuccess()
  return
}


type MarsServiceProcessor struct {
  processorMap map[string]thrift.TProcessorFunction
  handler MarsService
}

func (p *MarsServiceProcessor) AddToProcessorMap(key string, processor thrift.TProcessorFunction) {
  p.processorMap[key] = processor
}

func (p *MarsServiceProcessor) GetProcessorFunction(key string) (processor thrift.TProcessorFunction, ok bool) {
  processor, ok = p.processorMap[key]
  return processor, ok
}

func (p *MarsServiceProcessor) ProcessorMap() map[string]thrift.TProcessorFunction {
  return p.processorMap
}

func NewMarsServiceProcessor(handler MarsService) *MarsServiceProcessor {

  self2 := &MarsServiceProcessor{handler:handler, processorMap:make(map[string]thrift.TProcessorFunction)}
  self2.processorMap["PublicInterface"] = &marsServiceProcessorPublicInterface{handler:handler}
return self2
}

func (p *MarsServiceProcessor) Process(iprot, oprot thrift.TProtocol) (success bool, err thrift.TException) {
  name, _, seqId, err := iprot.ReadMessageBegin()
  if err != nil { return false, err }
  if processor, ok := p.GetProcessorFunction(name); ok {
    return processor.Process(seqId, iprot, oprot)
  }
  iprot.Skip(thrift.STRUCT)
  iprot.ReadMessageEnd()
  x3 := thrift.NewTApplicationException(thrift.UNKNOWN_METHOD, "Unknown function " + name)
  oprot.WriteMessageBegin(name, thrift.EXCEPTION, seqId)
  x3.Write(oprot)
  oprot.WriteMessageEnd()
  oprot.Flush()
  return false, x3

}

type marsServiceProcessorPublicInterface struct {
  handler MarsService
}

func (p *marsServiceProcessorPublicInterface) Process(seqId int32, iprot, oprot thrift.TProtocol) (success bool, err thrift.TException) {
  args := MarsServicePublicInterfaceArgs{}
  if err = args.Read(iprot); err != nil {
    iprot.ReadMessageEnd()
    x := thrift.NewTApplicationException(thrift.PROTOCOL_ERROR, err.Error())
    oprot.WriteMessageBegin("PublicInterface", thrift.EXCEPTION, seqId)
    x.Write(oprot)
    oprot.WriteMessageEnd()
    oprot.Flush()
    return false, err
  }

  iprot.ReadMessageEnd()
  result := MarsServicePublicInterfaceResult{}
var retval *base.MarsResponse
  var err2 error
  if retval, err2 = p.handler.PublicInterface(args.Req, args.Trace); err2 != nil {
    x := thrift.NewTApplicationException(thrift.INTERNAL_ERROR, "Internal error processing PublicInterface: " + err2.Error())
    oprot.WriteMessageBegin("PublicInterface", thrift.EXCEPTION, seqId)
    x.Write(oprot)
    oprot.WriteMessageEnd()
    oprot.Flush()
    return true, err2
  } else {
    result.Success = retval
}
  if err2 = oprot.WriteMessageBegin("PublicInterface", thrift.REPLY, seqId); err2 != nil {
    err = err2
  }
  if err2 = result.Write(oprot); err == nil && err2 != nil {
    err = err2
  }
  if err2 = oprot.WriteMessageEnd(); err == nil && err2 != nil {
    err = err2
  }
  if err2 = oprot.Flush(); err == nil && err2 != nil {
    err = err2
  }
  if err != nil {
    return
  }
  return true, err
}


// HELPER FUNCTIONS AND STRUCTURES

// Attributes:
//  - Req
//  - Trace
type MarsServicePublicInterfaceArgs struct {
  Req *base.MarsRequest `thrift:"req,1" db:"req" json:"req"`
  Trace *base.Trace `thrift:"trace,2" db:"trace" json:"trace"`
}

func NewMarsServicePublicInterfaceArgs() *MarsServicePublicInterfaceArgs {
  return &MarsServicePublicInterfaceArgs{}
}

var MarsServicePublicInterfaceArgs_Req_DEFAULT *base.MarsRequest
func (p *MarsServicePublicInterfaceArgs) GetReq() *base.MarsRequest {
  if !p.IsSetReq() {
    return MarsServicePublicInterfaceArgs_Req_DEFAULT
  }
return p.Req
}
var MarsServicePublicInterfaceArgs_Trace_DEFAULT *base.Trace
func (p *MarsServicePublicInterfaceArgs) GetTrace() *base.Trace {
  if !p.IsSetTrace() {
    return MarsServicePublicInterfaceArgs_Trace_DEFAULT
  }
return p.Trace
}
func (p *MarsServicePublicInterfaceArgs) IsSetReq() bool {
  return p.Req != nil
}

func (p *MarsServicePublicInterfaceArgs) IsSetTrace() bool {
  return p.Trace != nil
}

func (p *MarsServicePublicInterfaceArgs) Read(iprot thrift.TProtocol) error {
  if _, err := iprot.ReadStructBegin(); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
  }


  for {
    _, fieldTypeId, fieldId, err := iprot.ReadFieldBegin()
    if err != nil {
      return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
    }
    if fieldTypeId == thrift.STOP { break; }
    switch fieldId {
    case 1:
      if err := p.ReadField1(iprot); err != nil {
        return err
      }
    case 2:
      if err := p.ReadField2(iprot); err != nil {
        return err
      }
    default:
      if err := iprot.Skip(fieldTypeId); err != nil {
        return err
      }
    }
    if err := iprot.ReadFieldEnd(); err != nil {
      return err
    }
  }
  if err := iprot.ReadStructEnd(); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
  }
  return nil
}

func (p *MarsServicePublicInterfaceArgs)  ReadField1(iprot thrift.TProtocol) error {
  p.Req = &base.MarsRequest{}
  if err := p.Req.Read(iprot); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T error reading struct: ", p.Req), err)
  }
  return nil
}

func (p *MarsServicePublicInterfaceArgs)  ReadField2(iprot thrift.TProtocol) error {
  p.Trace = &base.Trace{}
  if err := p.Trace.Read(iprot); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T error reading struct: ", p.Trace), err)
  }
  return nil
}

func (p *MarsServicePublicInterfaceArgs) Write(oprot thrift.TProtocol) error {
  if err := oprot.WriteStructBegin("PublicInterface_args"); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err) }
  if p != nil {
    if err := p.writeField1(oprot); err != nil { return err }
    if err := p.writeField2(oprot); err != nil { return err }
  }
  if err := oprot.WriteFieldStop(); err != nil {
    return thrift.PrependError("write field stop error: ", err) }
  if err := oprot.WriteStructEnd(); err != nil {
    return thrift.PrependError("write struct stop error: ", err) }
  return nil
}

func (p *MarsServicePublicInterfaceArgs) writeField1(oprot thrift.TProtocol) (err error) {
  if err := oprot.WriteFieldBegin("req", thrift.STRUCT, 1); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field begin error 1:req: ", p), err) }
  if err := p.Req.Write(oprot); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T error writing struct: ", p.Req), err)
  }
  if err := oprot.WriteFieldEnd(); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field end error 1:req: ", p), err) }
  return err
}

func (p *MarsServicePublicInterfaceArgs) writeField2(oprot thrift.TProtocol) (err error) {
  if err := oprot.WriteFieldBegin("trace", thrift.STRUCT, 2); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field begin error 2:trace: ", p), err) }
  if err := p.Trace.Write(oprot); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T error writing struct: ", p.Trace), err)
  }
  if err := oprot.WriteFieldEnd(); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field end error 2:trace: ", p), err) }
  return err
}

func (p *MarsServicePublicInterfaceArgs) String() string {
  if p == nil {
    return "<nil>"
  }
  return fmt.Sprintf("MarsServicePublicInterfaceArgs(%+v)", *p)
}

// Attributes:
//  - Success
type MarsServicePublicInterfaceResult struct {
  Success *base.MarsResponse `thrift:"success,0" db:"success" json:"success,omitempty"`
}

func NewMarsServicePublicInterfaceResult() *MarsServicePublicInterfaceResult {
  return &MarsServicePublicInterfaceResult{}
}

var MarsServicePublicInterfaceResult_Success_DEFAULT *base.MarsResponse
func (p *MarsServicePublicInterfaceResult) GetSuccess() *base.MarsResponse {
  if !p.IsSetSuccess() {
    return MarsServicePublicInterfaceResult_Success_DEFAULT
  }
return p.Success
}
func (p *MarsServicePublicInterfaceResult) IsSetSuccess() bool {
  return p.Success != nil
}

func (p *MarsServicePublicInterfaceResult) Read(iprot thrift.TProtocol) error {
  if _, err := iprot.ReadStructBegin(); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
  }


  for {
    _, fieldTypeId, fieldId, err := iprot.ReadFieldBegin()
    if err != nil {
      return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
    }
    if fieldTypeId == thrift.STOP { break; }
    switch fieldId {
    case 0:
      if err := p.ReadField0(iprot); err != nil {
        return err
      }
    default:
      if err := iprot.Skip(fieldTypeId); err != nil {
        return err
      }
    }
    if err := iprot.ReadFieldEnd(); err != nil {
      return err
    }
  }
  if err := iprot.ReadStructEnd(); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
  }
  return nil
}

func (p *MarsServicePublicInterfaceResult)  ReadField0(iprot thrift.TProtocol) error {
  p.Success = &base.MarsResponse{}
  if err := p.Success.Read(iprot); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T error reading struct: ", p.Success), err)
  }
  return nil
}

func (p *MarsServicePublicInterfaceResult) Write(oprot thrift.TProtocol) error {
  if err := oprot.WriteStructBegin("PublicInterface_result"); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err) }
  if p != nil {
    if err := p.writeField0(oprot); err != nil { return err }
  }
  if err := oprot.WriteFieldStop(); err != nil {
    return thrift.PrependError("write field stop error: ", err) }
  if err := oprot.WriteStructEnd(); err != nil {
    return thrift.PrependError("write struct stop error: ", err) }
  return nil
}

func (p *MarsServicePublicInterfaceResult) writeField0(oprot thrift.TProtocol) (err error) {
  if p.IsSetSuccess() {
    if err := oprot.WriteFieldBegin("success", thrift.STRUCT, 0); err != nil {
      return thrift.PrependError(fmt.Sprintf("%T write field begin error 0:success: ", p), err) }
    if err := p.Success.Write(oprot); err != nil {
      return thrift.PrependError(fmt.Sprintf("%T error writing struct: ", p.Success), err)
    }
    if err := oprot.WriteFieldEnd(); err != nil {
      return thrift.PrependError(fmt.Sprintf("%T write field end error 0:success: ", p), err) }
  }
  return err
}

func (p *MarsServicePublicInterfaceResult) String() string {
  if p == nil {
    return "<nil>"
  }
  return fmt.Sprintf("MarsServicePublicInterfaceResult(%+v)", *p)
}


