#
# 开发环境配置文件
#
#########################################

# 全局配置
logfile                 = 'config/log.json'     # 日志存放位置，若配置后无对应的path, 则也会输出至os.Stdout default: os.Stdout
http_server_port        = 9308                  # 对接maybach的http服务端口

tip                     = '0.0.0.0'             # thrift服务绑定IP
tport                   = 10002                  # thrift服务监听端口
ttimeout                = '0ms'                 # 客户端超时时间

[redisCfg]
    redis_svr               = ["192.168.1.4:8379"]
    redis_conn_timeout      = 1000                      # redis连接超时 毫秒
    redis_read_timeout      = 500                       # redis读超时 毫秒
    redis_write_timeout     = 500                       # redis写超时 毫秒
    redis_max_idle          = 200                       # 最大空闲连接
    redis_max_active        = 2000                      # 最大活动连接
    redis_expire_second     = 600                       # redis数据过期时间 秒 线上配置10分钟 60

[javaThriftGW]
    host = "192.168.100.206"
    port = "18900"
    key = "fhA4hUoBcReZ8bJddPKkqCE42sn0PzoX"
    tokenexpire = 500

[downstreams]
     [downstreams.mars]
        servers             = [                     # 下游服务器IP端口列表
        ]
        healthythreshold    = 10                    # 健康阈值
        maxcooldowntime     = 30                    # 冷却时长
        minhealthyratio     = 1.0                   # 最小健康比
        connsize            = 1000                  # 每个地址对应的连接池大小
        timeout             = '30000ms'              # 超时时间
        cycle               = '1000ms'              # 健康检查的时间周期
        retrytimes          = 0                     # 创建连接失败重试次数
        maxconnfalsecnt     = 1                     # 单个连接允许出错次数，超过这个次数就close这个连接
        checkaliveconnsessioncycle  = '5m'          #多久檢查一次[kill 一段時間沒被使用的連線]
        connsessionalivetime        = '10m'         #多久沒被使用後, 就close這個Session

[apollo]
    apinamelistkey = "API_NAME_LIST"
    appid = "gw_example"
    cluster = "default"
    namespaceName = "application"
    configserver = "apollo-fat.kb.com"

[apollodefault]
    apinamelist = ["mars"]
    [apollodefault.apiinfo]
        [apollodefault.apiinfo.mars]
            servers             = [
                "192.168.1.3:16601"
            ]
            protocol = "thrift"